### ISSUE TITLE
superputty not coming up

### ISSUE THREAD

**Issue by souradeep100** [jimradford/superputty#615]
I am facing a problem, whenever I am double clicking superputty.exe , it is starting but the gui is not coming in the front. I can see in the task manager that the process superputty has started, but nothing is coming. I have tried with admin privilege, compatibility mode . I am having win 7.

**Comment by mangox** [comment]
Can you check your .NET version in your Win7  and paste the version here ?

**Comment by souradeep100** [comment]
4.5.51209 is the .net version .

**Comment by mangox** [comment]
I checked the release code which was build based on .net 3.5. I'm not sure if you have installed this version.

**Comment by souradeep100** [comment]
I have got superputty 1.4.0.8 and 1.4.0.6 and both are not working.

**Comment by mangox** [comment]
Could you have a try to install .net 3.5? After installing .net3.5, you can try to run SuperPutty again.
You can download the target version from the following link:
https://www.microsoft.com/en-us/download/details.aspx?id=21

**Comment by george-vieira** [comment]
I found this to be a problem too, I noticed if the path where the session.xml config is found is missing, in my case it was a network share that wasn't "connected", it would silently fail. no error, nothing.
This isn't a great way to exit a program error and superputty should handle these problems better.

**Comment by scottgoering** [comment]
I had this same problem.  Would silently fail.  Tried downgrading/upgrading and nothing seemed to work.
Poked around and found the error logs, and saw this message:
`System.UriFormatException: Invalid URI: The hostname could not be parsed.`
which occurred while trying to check for updates.  Here's the whole trace:

> 2016-07-13 15:51:49,281 [1] ERROR SuperPutty.Program - Error in Main
> System.UriFormatException: Invalid URI: The hostname could not be parsed.
>    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
>    at System.Net.WebProxy.GetProxiesAuto(Uri destination, Int32& syncStatus)
>    at System.Net.ProxyScriptChain.GetNextProxy(Uri& proxy)
>    at System.Net.ProxyChain.ProxyEnumerator.MoveNext()
>    at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)
>    at System.Net.HttpWebRequest.FindServicePoint(Boolean forceFind)
>    at System.Net.HttpWebRequest.BeginSubmitRequest()
>    at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
>    at SuperPutty.httpRequest.MakeRequest(String url, Action`2 callback)
>    at SuperPutty.frmSuperPutty.checkForUpdatesToolStripMenuItem_Click(Object sender, EventArgs e)
>    at SuperPutty.frmSuperPutty..ctor()
>    at SuperPutty.Program.Main(String[] args)
> 2016-07-13 15:51:49,291 [1] INFO  SuperPutty.Program - Shutdown
> 

What I ended up doing was modifying the AutoUpdateCheck setting (set to False).  This allows the program to open successfully, for me.  I can still get SuperPutty to show the error message if I manually check for updates, via the Help menu.

I believe I've traced this down to my work's proxy/automatic configuration script (zScaler).  Once I turn that script off, I don't have any issues with starting SuperPutty or manually checking for updates.

**Comment by pmiller189** [comment]
@scottgoering Thanks for the tip! I ran as administrator to get it to start, then unchecked the flag in the options for it to check for updates. Now it doesn't require "run as administrator" to start up. Without doing that, the SuperPutty.exe would consume an entire CPU indefinitely after startup and the GUI would never come up.

**Comment by karthikeayan** [comment]
To capture the log I did,

```
C:\>"c:\Program Files (x86)\SuperPuTTY\SuperPutty.exe" > superputty.log 2> superputty_error.log
```

In superputty.log I see, 
```
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\karthik\AppData\Local\http___www.jimradford.com\SuperPutty.exe_Url_2ogbfhb2el1qutg2z2ptnyqlkqfyyi05\1.4.0.9\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
```

I don't understand this.

Just deleted "http_www.jimradford.com" folder inside "C:\Users\karthik\AppData\Local" and started SuperPutty, it started again.

One issue is that, it forgot the Putty location so I had to specify that agian.
