### ISSUE TITLE
Super Putty fails to start after updates to .NET framework

### ISSUE THREAD

**Issue by woodyman4916** [jimradford/superputty#726]

**Comment by woodyman4916** [comment]
Super Putty fails to start after Windows 10 update KB4480056. Log file below.

2019-01-12 07:53:52,111 [1] INFO  SuperPutty.Program - Starting
2019-01-12 07:53:52,119 [1] INFO  SuperPutty.SuperPuTTY - Initializing.  Version=1.4.0.9, UserSettings=C:\Users\bwood\SuperPuTTY.settings, SettingsFolder=
2019-01-12 07:53:52,143 [1] INFO  SuperPutty.SuperPuTTY - Loaded 38 icons from theme directory.  dir=C:\Program Files (x86)\SuperPuTTY\themes\default\icons
2019-01-12 07:53:52,146 [1] INFO  SuperPutty.Utils.SingleInstanceHelper - Registered IpcChannel and Service: [ipc://SuperPuTTY/SingleInstance]
2019-01-12 07:53:52,146 [1] INFO  SuperPutty.SuperPuTTY - Initialized
2019-01-12 07:53:52,216 [1] ERROR SuperPutty.Program - Error in Main
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\bwood\AppData\Local\http___www.jimradford.com\SuperPutty.exe_Url_2ogbfhb2el1qutg2z2ptnyqlkqfyyi05\1.4.0.9\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at SuperPutty.Properties.Settings.get_FileZillaExe()
   at SuperPutty.dlgFindPutty..ctor()
   at SuperPutty.dlgFindPutty.PuttyCheck()
   at SuperPutty.frmSuperPutty..ctor()
   at SuperPutty.Program.Main(String[] args)
2019-01-12 07:53:52,219 [1] INFO  SuperPutty.Program - Shutdown

**Comment by woodyman4916** [comment]
Corrupt user.config  Please disregard
