### ISSUE TITLE
Unable to configure SuperPutty

### ISSUE THREAD

**Issue by jagadishb4u** [jimradford/superputty#741]
**Describe the bug**

**To Reproduce**
1. Open SuerPutty by clicking ""C:\Program Files (x86)\SuperPuTTY\SuperPutty.exe"
2. Give the putty.exe path in "putty.exe Location (Required)"
3. Click "Ok" button.

**Expected behavior**
Super Putty window should open with the Menu bars and session explorer on the right hand side.

**Screenshots**
![image](https://user-images.githubusercontent.com/49143185/55777372-5bfae980-5abd-11e9-8338-28608a2b230b.png)

---------------------------
Application_ThreadException
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperPutty.Utils.PortableSettingsProvider.SetValue(SettingsPropertyValue propVal)
   at SuperPutty.Utils.PortableSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection collection)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at SuperPutty.dlgFindPutty.buttonOk_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
OK   
---------------------------

**Desktop (please complete the following information):**
 - OS: Windows 10 pro

**Additional context**
It suddenly stopped working, I have tried reinstalling Putty and SuperPutty, but still no luck.

**Comment by hsonner** [comment]
I had the same issue. The settings file  C:\Users\<username>\SuperPuTTY.settings had become corrupted. I renamed it and restarted  SuperPuTTY and was able to get around the issue.
