### ISSUE TITLE
SuperPutty crashes windows 10 1903

### ISSUE THREAD

**Issue by dustinreeves** [jimradford/superputty#783]
**Describe the bug**
SuperPutty fails to run. Looks like some type of  XML issue ?

2020-03-02 17:00:29,817 [1] ERROR SuperPutty.Program - Error in Main
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\wbdr5055\AppData\Local\http___www.jimradford.com\SuperPutty.exe_Url_2ogbfhb2el1qutg2z2ptnyqlkqfyyi05\1.4.0.9\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---

**To Reproduce**
Open superputty, fails with exception.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

[SuperPuTTY.20200302_170210.log](https://github.com/jimradford/superputty/files/4283384/SuperPuTTY.20200302_170210.log)
[SuperPuTTY.20200302_170205.log](https://github.com/jimradford/superputty/files/4283385/SuperPuTTY.20200302_170205.log)
[SuperPuTTY.20200302_170159.log](https://github.com/jimradford/superputty/files/4283386/SuperPuTTY.20200302_170159.log)
[SuperPuTTY.20200302_170153.log](https://github.com/jimradford/superputty/files/4283387/SuperPuTTY.20200302_170153.log)
[SuperPuTTY.20200302_170029.log](https://github.com/jimradford/superputty/files/4283388/SuperPuTTY.20200302_170029.log)

**Comment by dustinreeves** [comment]
well looks like the user.config file became corrupted somehow... i deleted the offending appdata folder and restored settings and everything came back up swingingly.  thanks for your time.
